name: Execute Test Case
on:
  workflow_dispatch:
    inputs:
      shardIndex:
        description: 'Provide shard indices (comma-separated)'
        required: true
        default: '1,2,3,4,5,6,7,8,9,10'
      shardTotal:
        description: 'Provide total number of shards'
        required: true
        default: 10

jobs:
  set_variables:
    runs-on: ubuntu-latest
    outputs:
      shardIndexArray: ${{ steps.set_vars.outputs.shardIndexArray }}
    steps:
      - name: Set shardIndex array
        id: set_vars
        run: |
          shardIndexArray=$(echo '["'${{ github.event.inputs.shardIndex }}'"]' | sed 's/,/","/g')
          echo "shardIndexArray=$shardIndexArray" >> $GITHUB_ENV
          echo "::set-output name=shardIndexArray::$shardIndexArray"
      - name: Debug Output
        run: echo "shardIndexArray=${{ steps.set_vars.outputs.shardIndexArray }}"

  test_smart_orchestration:
    runs-on: ubuntu-latest
    needs: set_variables
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set shardTotal environment variable
        run: echo "SHARD_TOTAL=${{ github.event.inputs.shardTotal }}" >> $GITHUB_ENV     
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Debug Output
        run: echo "${{ fromJson(needs.set_variables.outputs.shardIndexArray) }}"
      - name: Get test names
        id: getTestNames
        run: |
          test_names=$(node -e 'import("sharding-pk-play").then(module => console.log(module.orchestrateTestsForShard(${{ fromJson(needs.set_variables.outputs.shardIndexArray) }}))).catch(err => console.error(err))')
          echo "test_names=$test_names" >> $GITHUB_ENV
      - name: Run Playwright tests
        run: |
          npx playwright test --grep "${{ env.test_names }}"

  test_no_orchestration:
    needs: test_smart_orchestration
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Set shardTotal environment variable
        run: echo "SHARD_TOTAL=${{ github.event.inputs.shardTotal }}" >> $GITHUB_ENV
      - name: Debug Output
        run: echo "${{ fromJson(needs.set_variables.outputs.shardIndexArray) }}"     
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install
      - name: Run Playwright tests
        run: |
          npx playwright test --shard=${{ fromJson(needs.set_variables.outputs.shardIndexArray) }}/${{ github.event.inputs.shardTotal }}